version: '3.7'

services:
  web_dev:
    restart: always
    build: ./mascomunitario
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mascomunitario/:/usr/src/mascomunitario/
    ports:
      - 52000:8000
    env_file:
      - ./.env.dev
    links: 
      - db:db
    depends_on:
      - db
  db:
    restart: always
    image: postgres:12.0-alpine
    
    network_mode: host
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
      
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env.prod.pg
    ports:
      - "16543:80"
    links: 
      - db:db
    depends_on:
      - db

volumes:
  postgres_data:
