version: '3.7'

services:  
  web:
    restart: always
    build:
      context: ./mascomunitario
      dockerfile: Dockerfile.prod
    command: gunicorn mascomunitario.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./mascomunitario/static:/home/app/web/static
      - ./mascomunitario/media:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db_prod
  db_prod:
    restart: always
    image: postgres:12.0-alpine
    network_mode: host
    volumes:
      - ./postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db  
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - ./mascomunitario/static:/home/app/web/static
      - ./mascomunitario/media:/home/app/web/media
      #- /etc/ssl/certs/propios/unicesmag:/certs
    ports:
      - 80:80
      #- 443:443
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  media:
